/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBOUAS;
import com.sun.glass.ui.View;
import java.awt.Dialog;
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AfrizalNurkholik
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masuk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        Fnama = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Fasal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Ftujuan = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masuk.setText("Masuk");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });
        getContentPane().add(masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 520, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("FORM PEMESANAN BUS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 430, -1));

        jLabel19.setText("NAMA CALON PENUMPANG");

        Fnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnamaActionPerformed(evt);
            }
        });

        jLabel20.setText("TERMINAL");

        jLabel21.setText("TUJUAN PENUMPANG");

        submit.setText("Create");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Clear.setText("Clear");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(18, 18, 18)
                .addComponent(Clear)
                .addGap(62, 62, 62)
                .addComponent(back)
                .addGap(25, 25, 25))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(Fnama, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                        .addComponent(Fasal)
                        .addComponent(Ftujuan))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear)
                    .addComponent(back)
                    .addComponent(submit))
                .addGap(60, 60, 60))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jLabel19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Fnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jLabel20)
                    .addGap(18, 18, 18)
                    .addComponent(Fasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jLabel21)
                    .addGap(18, 18, 18)
                    .addComponent(Ftujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(131, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 89, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbouas/Gambar WhatsApp 2025-01-13 pukul 14.32.16_ec6a92c8.jpg"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 400));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nama ", "Asal", "Tujuan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, 402));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbouas/siapa-pemilik-po-bus-bus-primajasa-ternyata-ternyata-ini-orangnya-ZG1tEF6ZbE.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
   new view().setVisible(true);
    }//GEN-LAST:event_masukActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String NAMA, ASAL, TUJUAN, query;
  
    try {
        Class.forName("com.mysql.jdbc.Driver");
        
        String url = "jdbc:mysql://localhost:3306/java_user";
          String user = "root";  
          String password = "";  
        
        Connection con = DriverManager.getConnection(url, user, password);
        Statement st = con.createStatement();
        
        if ("".equals(Fnama.getText())) { 
            JOptionPane.showMessageDialog(new JFrame(), "Nama Calon Penumpang Harus Diisi", "Dialog", JOptionPane.ERROR_MESSAGE);
        } else if ("".equals(Fasal.getText())) { 
            JOptionPane.showMessageDialog(new JFrame(), "Asal Harus Diisi", "Dialog", JOptionPane.ERROR_MESSAGE);
        } else if("".equals(Ftujuan.getText())) { 
            JOptionPane.showMessageDialog(new JFrame(), "Tujuan Harus Diisi", "Dialog", JOptionPane.ERROR_MESSAGE);
        } else {
            NAMA = Fnama.getText();
            ASAL = Fasal.getText(); // Menggunakan format waktu
            TUJUAN = Ftujuan.getText();
            
            query = "INSERT INTO db_bs (Nama, Asal, Tujuan) VALUES ('" + NAMA + "','" + ASAL + "','" + TUJUAN + "')";
            System.out.println("Nama: " + NAMA + ", Asal: " + ASAL + ", Tujuan: " + TUJUAN);
            
            st.executeUpdate(query);
            Fnama.setText("");
            Fasal.setText("");
            Ftujuan.setText("");
            
            JOptionPane.showMessageDialog(null, "Register Successfully processed.");
            loadData(); // Memanggil metode loadData() untuk memperbarui tabel
            con.close();
        }
    } catch(Exception e) {
        
        System.out.println("Error: " + e.getMessage());}
    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new navigasi().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void FnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnamaActionPerformed

    public void loadData() throws SQLException{
         try {
         Class.forName("com.mysql.jdbc.Driver");
          
          String url = "jdbc:mysql://localhost:3306/java_user";
          String user = "root";  
          String password = "";  
          
          
     Connection con = DriverManager.getConnection(url, user, password);
     Statement st = con.createStatement();
     DefaultTableModel model = new DefaultTableModel(new String[]{"id", "Nama Penumpang","Asal Penumpang","Tujuan Penumpang"}, 0);
             
      table.setModel(model);
      // SQL query to fetch data from the database
      String sql = "SELECT `id`, `Nama`, `Asal`, `Tujuan` FROM `java_user`.`db_bs`";

      ResultSet rs = st.executeQuery(sql);
      String i, n, a, t;
      while(rs.next()) {
      i = rs.getString("id");
      n = rs.getString("Nama");
      a = rs.getString("Asal");
      t = rs.getString("Tujuan");
      model.addRow(new Object[]{i, n, a, t});
      }
      con.close();
       }
      catch(Exception e){
      System.out.println("Error" + e.getMessage());
      }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField Fasal;
    private javax.swing.JTextField Fnama;
    private javax.swing.JTextField Ftujuan;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton masuk;
    private javax.swing.JButton submit;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
